# Base configuration
title: Eugene Obrezkov aka ghaiklor
description: Software Engineer · Node.js · Rust · D2D | Passionate about programming languages, compilers, tools
keywords: Eugene Obrezkov, Eugene, Obrezkov, ghaiklor, JavaScript, NodeJS, DevOps, Compilers, Interpreters, Operating Systems
url: http://ghaiklor.com
